// ============================================
// INDUSTRY THEMES
// Color schemes, fonts, and styling per industry
// ============================================

const THEMES = {
  autoDetailing: {
    id: 'autoDetailing',
    name: 'Auto Detailing',
    primaryColor: '#d97706',
    accentColor: '#f59e0b',
    bgColor: '#020617',
    surfaceColor: '#0f172a',
    textColor: '#ffffff',
    textMuted: 'rgba(255,255,255,0.6)',
    headingFont: 'Montserrat',
    bodyFont: 'Rajdhani',
    fontImport: "https://fonts.googleapis.com/css2?family=Rajdhani:wght@400;500;600;700&family=Montserrat:wght@400;500;600;700;800&display=swap",
    borderRadius: '16px',
    buttonRadius: '50px',
    borderAccent: 'rgba(255,255,255,0.1)',
    borderAccentHover: 'rgba(217, 119, 6, 0.4)',
  },
  'autoDetailing-light': {
    id: 'autoDetailing-light',
    name: 'Auto Detailing (Light)',
    primaryColor: '#d97706',        // amber orange — same brand colour
    accentColor: '#f59e0b',         // golden yellow accent
    bgColor: '#ffffff',             // clean white page background
    surfaceColor: '#fafafa',        // near-white for cards/panels
    textColor: '#111827',           // near-black body text
    textMuted: 'rgba(17,24,39,0.55)',
    headingFont: 'Montserrat',      // same premium fonts
    bodyFont: 'Rajdhani',
    fontImport: "https://fonts.googleapis.com/css2?family=Rajdhani:wght@400;500;600;700&family=Montserrat:wght@400;500;600;700;800&display=swap",
    borderRadius: '16px',
    buttonRadius: '50px',
    borderAccent: 'rgba(217,119,6,0.15)',
    borderAccentHover: 'rgba(217,119,6,0.35)',
  },
  landscaping: {
    id: 'landscaping',
    name: 'Landscaping',
    primaryColor: '#1a3a1a',
    accentColor: '#7cb342',
    bgColor: '#faf8f3',
    surfaceColor: '#f0ece3',
    textColor: '#2d2d2d',
    textMuted: 'rgba(45,45,45,0.7)',
    headingFont: 'Lora',
    bodyFont: 'Archivo',
    fontImport: "https://fonts.googleapis.com/css2?family=Lora:wght@400;500;600;700&family=Archivo:wght@400;500;600;700&display=swap",
    borderRadius: '15px',
    buttonRadius: '50px',
    borderAccent: 'rgba(124, 179, 66, 0.2)',
    borderAccentHover: 'rgba(124, 179, 66, 0.4)',
  },
  salonSpa: {
    id: 'salonSpa',
    name: 'Salon & Spa',
    primaryColor: '#B76E79',
    accentColor: '#8B4C5C',
    bgColor: '#FAF7F2',
    surfaceColor: '#F0EBE3',
    textColor: '#2C2C2C',
    textMuted: 'rgba(44,44,44,0.7)',
    headingFont: 'Cormorant Garamond',
    bodyFont: 'Montserrat',
    fontImport: "https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@400;500;600;700&family=Montserrat:wght@400;500;600;700&display=swap",
    borderRadius: '20px',
    buttonRadius: '50px',
    borderAccent: 'rgba(183, 110, 121, 0.2)',
    borderAccentHover: 'rgba(183, 110, 121, 0.4)',
  },
  restaurant: {
    id: 'restaurant',
    name: 'Restaurant',
    primaryColor: '#6B4423',
    accentColor: '#D4AF37',
    bgColor: '#FFFFFF',
    surfaceColor: '#F5E6D3',
    textColor: '#3E2723',
    textMuted: 'rgba(62,39,35,0.7)',
    headingFont: 'Playfair Display',
    bodyFont: 'Open Sans',
    fontImport: "https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;500;600;700;800&family=Open+Sans:wght@400;500;600;700&display=swap",
    borderRadius: '15px',
    buttonRadius: '50px',
    borderAccent: 'rgba(107, 68, 35, 0.2)',
    borderAccentHover: 'rgba(107, 68, 35, 0.4)',
  },
  fitness: {
    id: 'fitness',
    name: 'Fitness',
    primaryColor: '#0EA5E9',
    accentColor: '#FACC15',
    bgColor: '#0A0A0A',
    surfaceColor: '#1A1A1A',
    textColor: '#FFFFFF',
    textMuted: 'rgba(255,255,255,0.7)',
    headingFont: 'Bebas Neue',
    bodyFont: 'Roboto',
    fontImport: "https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Roboto:wght@400;500;700&display=swap",
    borderRadius: '12px',
    buttonRadius: '8px',
    borderAccent: 'rgba(14, 165, 233, 0.2)',
    borderAccentHover: 'rgba(14, 165, 233, 0.4)',
  },
  dental: {
    id: 'dental',
    name: 'Dental',
    primaryColor: '#14B8A6',
    accentColor: '#0F766E',
    bgColor: '#FFFFFF',
    surfaceColor: '#F8FAFC',
    textColor: '#1E293B',
    textMuted: 'rgba(30,41,59,0.7)',
    headingFont: 'Nunito Sans',
    bodyFont: 'Inter',
    fontImport: "https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@400;600;700;800&family=Inter:wght@400;500;600;700&display=swap",
    borderRadius: '16px',
    buttonRadius: '50px',
    borderAccent: 'rgba(20, 184, 166, 0.2)',
    borderAccentHover: 'rgba(20, 184, 166, 0.4)',
  },
  hvac: {
    id: 'hvac',
    name: 'HVAC & Plumbing',
    primaryColor: '#F97316',
    accentColor: '#1E40AF',
    bgColor: '#FFFFFF',
    surfaceColor: '#F1F5F9',
    textColor: '#1F2937',
    textMuted: 'rgba(31,41,55,0.7)',
    headingFont: 'Oswald',
    bodyFont: 'Work Sans',
    fontImport: "https://fonts.googleapis.com/css2?family=Oswald:wght@400;500;600;700&family=Work+Sans:wght@400;500;600;700&display=swap",
    borderRadius: '12px',
    buttonRadius: '8px',
    borderAccent: 'rgba(249, 115, 22, 0.2)',
    borderAccentHover: 'rgba(249, 115, 22, 0.4)',
  },
  cleaning: {
    id: 'cleaning',
    name: 'Cleaning',
    primaryColor: '#1D6FA4',
    accentColor: '#0EA5E9',
    bgColor: '#FFFFFF',
    surfaceColor: '#F0F9FF',
    textColor: '#1F2937',
    textMuted: 'rgba(31,41,55,0.7)',
    headingFont: 'Rubik',
    bodyFont: 'Karla',
    fontImport: "https://fonts.googleapis.com/css2?family=Rubik:wght@400;500;600;700&family=Karla:wght@400;500;600;700&display=swap",
    borderRadius: '16px',
    buttonRadius: '50px',
    borderAccent: 'rgba(29, 111, 164, 0.2)',
    borderAccentHover: 'rgba(29, 111, 164, 0.4)',
  },
  'cleaning-green': {
    id: 'cleaning-green',
    name: 'Cleaning (Green)',
    primaryColor: '#16A34A',
    accentColor: '#22C55E',
    bgColor: '#FFFFFF',
    surfaceColor: '#F0FDF4',
    textColor: '#1F2937',
    textMuted: 'rgba(31,41,55,0.7)',
    headingFont: 'Rubik',
    bodyFont: 'Karla',
    fontImport: "https://fonts.googleapis.com/css2?family=Rubik:wght@400;500;600;700&family=Karla:wght@400;500;600;700&display=swap",
    borderRadius: '16px',
    buttonRadius: '50px',
    borderAccent: 'rgba(22, 163, 74, 0.2)',
    borderAccentHover: 'rgba(22, 163, 74, 0.4)',
  },
  realEstate: {
    id: 'realEstate',
    name: 'Real Estate',
    primaryColor: '#1E3A8A',
    accentColor: '#F59E0B',
    bgColor: '#FFFFFF',
    surfaceColor: '#F3F4F6',
    textColor: '#1F2937',
    textMuted: 'rgba(31,41,55,0.7)',
    headingFont: 'Merriweather',
    bodyFont: 'Lato',
    fontImport: "https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700;900&family=Lato:wght@400;700&display=swap",
    borderRadius: '12px',
    buttonRadius: '8px',
    borderAccent: 'rgba(30, 58, 138, 0.2)',
    borderAccentHover: 'rgba(30, 58, 138, 0.4)',
  },
  // ── Photography: 3 style variants (warm / dark / clean) ──────────────
  // The schema generator picks one randomly and embeds its themeId.
  // generateV2.js reads themeId and selects the right sub-theme.
  photography: {
    // Default alias → warm (used as fallback by getThemeForBusinessType)
    id: 'photography',
    name: 'Photography',
    primaryColor: '#1c1917',
    accentColor: '#78716c',
    bgColor: '#faf9f6',
    surfaceColor: '#f0ede6',
    textColor: '#1c1917',
    textMuted: 'rgba(28,25,23,0.55)',
    headingFont: 'Cormorant Garamond',
    bodyFont: 'Inter',
    fontImport: "https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,400;0,500;0,600;0,700;1,400;1,600&family=Inter:wght@300;400;500;600;700&display=swap",
    borderRadius: '16px',
    buttonRadius: '50px',
    borderAccent: 'rgba(28,25,23,0.2)',
    borderAccentHover: 'rgba(28,25,23,0.5)',
  },
  'photography-warm': {
    // Warm stone: cream background, natural tones, serif editorial
    id: 'photography-warm',
    name: 'Photography — Warm',
    primaryColor: '#1c1917',
    accentColor: '#78716c',
    bgColor: '#faf9f6',
    surfaceColor: '#f0ede6',
    textColor: '#1c1917',
    textMuted: 'rgba(28,25,23,0.55)',
    headingFont: 'Cormorant Garamond',
    bodyFont: 'Inter',
    fontImport: "https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,400;0,500;0,600;0,700;1,400;1,600&family=Inter:wght@300;400;500;600;700&display=swap",
    borderRadius: '16px',
    buttonRadius: '50px',
    borderAccent: 'rgba(28,25,23,0.2)',
    borderAccentHover: 'rgba(28,25,23,0.5)',
  },
  'photography-dark': {
    // Moody dark: near-black background, warm gold accents, cinematic
    id: 'photography-dark',
    name: 'Photography — Dark',
    primaryColor: '#f0ede6',        // light for buttons on dark bg
    accentColor: '#c9ad87',         // warm gold
    bgColor: '#0d0d0d',
    surfaceColor: '#1a1a1a',
    textColor: '#f0ede6',
    textMuted: 'rgba(240,237,230,0.55)',
    headingFont: 'Cormorant Garamond',
    bodyFont: 'Raleway',
    fontImport: "https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,400;0,500;0,600;0,700;1,400;1,600&family=Raleway:wght@300;400;500;600;700&display=swap",
    borderRadius: '8px',
    buttonRadius: '2px',
    borderAccent: 'rgba(240,237,230,0.15)',
    borderAccentHover: 'rgba(240,237,230,0.4)',
  },
  'photography-clean': {
    // Minimal white: pure white, sharp edges, high contrast, modern
    id: 'photography-clean',
    name: 'Photography — Clean',
    primaryColor: '#111111',
    accentColor: '#888888',
    bgColor: '#ffffff',
    surfaceColor: '#f5f5f5',
    textColor: '#111111',
    textMuted: 'rgba(17,17,17,0.5)',
    headingFont: 'Playfair Display',
    bodyFont: 'Lato',
    fontImport: "https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,500;0,700;1,400;1,700&family=Lato:wght@300;400;700&display=swap",
    borderRadius: '0px',
    buttonRadius: '0px',
    borderAccent: 'rgba(17,17,17,0.15)',
    borderAccentHover: 'rgba(17,17,17,0.5)',
  },
  legal: {
    id: 'legal',
    name: 'Legal',
    primaryColor: '#7C2D12',
    accentColor: '#CA8A04',
    bgColor: '#FFFFFF',
    surfaceColor: '#FEF3C7',
    textColor: '#1C1917',
    textMuted: 'rgba(28,25,23,0.7)',
    headingFont: 'EB Garamond',
    bodyFont: 'Source Sans Pro',
    fontImport: "https://fonts.googleapis.com/css2?family=EB+Garamond:wght@400;500;600;700&family=Source+Sans+Pro:wght@400;600;700&display=swap",
    borderRadius: '8px',
    buttonRadius: '6px',
    borderAccent: 'rgba(124, 45, 18, 0.2)',
    borderAccentHover: 'rgba(124, 45, 18, 0.4)',
  },
  renovation: {
    id: 'renovation',
    name: 'Handyman & Renovation',
    primaryColor: '#b45309',
    accentColor: '#d97706',
    bgColor: '#f8fafc',
    surfaceColor: '#f1f5f9',
    textColor: '#0f172a',
    textMuted: 'rgba(15,23,42,0.6)',
    headingFont: 'Roboto Slab',
    bodyFont: 'Inter',
    fontImport: "https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=Roboto+Slab:wght@400;500;600;700;800&display=swap",
    borderRadius: '8px',
    buttonRadius: '4px',
    borderAccent: 'rgba(180,83,9,0.2)',
    borderAccentHover: 'rgba(180,83,9,0.5)',
  },
  organic: {
    id: 'organic',
    name: 'Organic',
    primaryColor: '#6b8f5e',
    accentColor: '#85a378',
    bgColor: '#faf8f5',
    surfaceColor: '#f0ece5',
    textColor: '#1b2216',
    textMuted: 'rgba(27,34,22,0.65)',
    headingFont: 'Cormorant Garamond',
    bodyFont: 'Inter',
    fontImport: "https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,400;0,500;0,600;0,700;1,400;1,600&family=Inter:wght@400;500;600;700&display=swap",
    borderRadius: '16px',
    buttonRadius: '50px',
    borderAccent: 'rgba(107,143,94,0.2)',
    borderAccentHover: 'rgba(107,143,94,0.4)',
  },
  petGrooming: {
    id: 'petGrooming',
    name: 'Pet Grooming',
    primaryColor: '#9333EA',
    accentColor: '#6EE7B7',
    bgColor: '#FFFFFF',
    surfaceColor: '#FEF3C7',
    textColor: '#374151',
    textMuted: 'rgba(55,65,81,0.7)',
    headingFont: 'Quicksand',
    bodyFont: 'Poppins',
    fontImport: "https://fonts.googleapis.com/css2?family=Quicksand:wght@400;500;600;700&family=Poppins:wght@400;500;600;700&display=swap",
    borderRadius: '20px',
    buttonRadius: '50px',
    borderAccent: 'rgba(147, 51, 234, 0.2)',
    borderAccentHover: 'rgba(147, 51, 234, 0.4)',
  },
};

// Map business type to theme (same logic as templates-enhanced.js)
function getThemeForBusinessType(businessType) {
  const bt = businessType.toLowerCase();
  const keywordMap = {
    restaurant: ['restaurant', 'cafe', 'bistro', 'dining', 'eatery', 'bar', 'grill', 'food'],
    fitness: ['gym', 'fitness', 'training', 'crossfit', 'yoga', 'pilates', 'workout'],
    dental: ['dental', 'dentist', 'orthodonti', 'teeth', 'oral'],
    realEstate: ['real estate', 'realtor', 'property', 'homes', 'houses', 'realty'],
    petGrooming: ['pet', 'grooming', 'dog', 'cat', 'veterinary', 'vet', 'animal'],
    hvac: ['hvac', 'heating', 'cooling', 'air conditioning', 'furnace', 'plumbing', 'ac repair'],
    photography: ['photography', 'photographer', 'photo', 'wedding photography', 'portrait'],
    cleaning: ['cleaning', 'maid', 'janitorial', 'housekeeping', 'clean'],
    legal: ['law', 'legal', 'attorney', 'lawyer'],
    renovation: ['renovation', 'remodeling', 'contractor', 'construction', 'remodel', 'builder', 'handyman', 'repair'],
    salonSpa: ['salon', 'spa', 'massage', 'facial', 'beauty', 'wellness', 'hair', 'nail', 'esthetician'],
    autoDetailing: ['detailing', 'car', 'auto', 'vehicle', 'ceramic', 'paint', 'wash'],
    organic: ['landscaping', 'lawn', 'garden', 'tree', 'outdoor', 'yard'],
  };

  for (const [themeKey, keywords] of Object.entries(keywordMap)) {
    if (keywords.some(kw => bt.includes(kw))) {
      // Cleaning alternates between blue and green variants for variety
      if (themeKey === 'cleaning') {
        return Math.random() < 0.5 ? THEMES['cleaning'] : THEMES['cleaning-green'];
      }
      // Auto detailing alternates between dark and light variants
      if (themeKey === 'autoDetailing') {
        return Math.random() < 0.5 ? THEMES['autoDetailing'] : THEMES['autoDetailing-light'];
      }
      return THEMES[themeKey];
    }
  }
  return THEMES.organic; // default
}

module.exports = { THEMES, getThemeForBusinessType };
